apiVersion: v2
name: device-metrics-exporter-charts
description: A Helm chart for AMD Device Metric Exporter
keywords:
  - kubernetes
  - cluster
  - hardware
  - amd
  - gpu
  - monitoring
  - prometheus

type: application
version: v1.4.1
appVersion: "v1.4.1"
kubeVersion: ">= 1.29.0-0"

maintainers:
- email: prshanmug@amd.com
  name: Praveen Kumar Shanmugam
- email: yan.sun3@amd.com
  name: Yan Sun
- email: shrey.ajmera@amd.com
  name: Shrey Ajmera
